---
# some setup of the current "old" compute VMs
- hosts: compute
  become: yes
  gather_facts: yes

  tasks:

  - name: "set NLTK data directory in /etc/environment -- see build.py for setting up sagemath"
    tags: [install, update]
    lineinfile: 'dest=/etc/environment regexp=^NLTK_DATA= line=NLTK_DATA="/usr/share/nltk_data"'

  - name: "directory $NLTK_DATA"
    tags: [install, update]
    shell: 'mkdir -d $NLTK_DATA; chown -R salvus. $NLTK_DATA; chmod go=rx $NLTK_DATA'

  - name: "download it"
    tags: [install, update]
    shell: 'umask 022; sage -python -m nltk.downloader all'
