---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: "group 'showpid'"
    group: name=showpid state=present system=yes
    tags: users

  - name: "add user 'salvus' to 'showpid'"
    user: name=salvus groups=showpid append=yes
    tags: users

  - name: "user 'monitor' is a systems account in 'showpid'"
    user: name=monitor system=yes shell=/bin/bash groups=showpid append=yes
    tags: users

  - name: "ssh keys for 'monitor'"
    authorized_key: user=monitor key="{{ lookup('file', 'files/gomonitor.pub') }}"
    tags: users

  - name: "proc hide processes for users"
    lineinfile: dest=/etc/fstab
                regexp='^proc'
                line='proc /proc proc defaults,hidepid=2,gid=showpid 0 0'
    notify: remount proc


  handlers:

  - name: remount proc
    command: mount -o remount,rw,hidepid=2,gid=showpid /proc
