---
# install the julia programming language from the ubuntu PPA on all compute nodes
# https://launchpad.net/~staticfloat/+archive/ubuntu/juliareleases
# https://launchpad.net/~staticfloat/+archive/ubuntu/julia-deps

- hosts: compute
  become: yes
  gather_facts: no # set it to yes, if you need to use {{ ansible_distribution_release }} to know if it is vivid etc.

  tasks:

  - name: "julia ppa"
    apt_repository: repo='ppa:staticfloat/juliareleases'

  - name: "julia dependencies ppa"
    apt_repository: repo='ppa:staticfloat/julia-deps'

  # update apt cache and upgrade using aptitude's heuristics
  - name: "apt-get update & upgrade"
    apt: update_cache=yes upgrade=safe

  - name: "apt-get install packages"
    apt: state=latest name={{ item }}
    with_items:
       - julia
       - julia-doc
