---
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: 'create target directory'
    file: path=/usr/local/share/latexmk/ state=directory

  # support for sagetex for latexmk by default
  # see https://github.com/dandrake/sagetex/wiki
  - name: "copy latexmkrc file to /usr/local/share/latexmk/"
    copy: src=files/latexmkrc
          dest=/usr/local/share/latexmk/latexmkrc
          owner=root group=root mode=644