---
- hosts: compute
  become: salvus
  strategy: free
  gather_facts: no

  tasks:
  - name: "install prometheus compute python file"
    copy: src="files/prometheus_compute.py"
          dest="~/bin/prometheus_compute.py"
          owner=salvus group=salvus mode=700
    register: copyfile

  - name: "install prometheus compute control file"
    copy: src="files/prometheus_compute.sh"
          dest="~/bin/prometheus_compute.sh"
          owner=salvus group=salvus mode=700

  - name: "restart daemon if necessary"
    shell: "/home/salvus/bin/prometheus_compute.sh restart"
    when: copyfile.changed

  - name: "crontab @reboot entry for prometheus_compute"
    cron: special_time=reboot
          job="/home/salvus/bin/prometheus_compute.sh start" 
          name="prometheus_compute monitoring"
          user=salvus

