---
# tuning sysctl parameters
- hosts: compute
  become: yes
  gather_facts: no

  tasks:

  - name: "install 99-smc.conf sysctl.d file on compute nodes"
    template: src=files/sysctl-compute.conf
              dest=/etc/sysctl.d/99-smc.conf
              owner=root group=root mode="u=rw,g=r,o=r"
    register: sysctl

  - name: "reload entire sysctl configuration"
    command: "sysctl --system"
    when: sysctl.changed

- hosts: db:web
  become: yes
  gather_facts: no
  tags : db

  tasks:

  - name: "install 99-smc.conf sysctl.d file on DB and WEB nodes"
    template: src=files/sysctl-db.conf
              dest=/etc/sysctl.d/99-smc.conf
              owner=root group=root mode="u=rw,g=r,o=r"
    register: sysctl

  - name: "reload entire sysctl configuration"
    command: "sysctl --system"
    when: sysctl.changed
