apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 2
  labels:
    run: smc-hub
  name: smc-hub
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      run: smc-hub
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: smc-hub
    spec:
      containers:
      - image: {image}
        imagePullPolicy:  IfNotPresent
        name: smc-hub
        ports:
        - containerPort: 5000
          protocol: TCP
        - containerPort: 5001
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /alive
            port: 5000
            scheme: HTTP
          timeoutSeconds: 1
        volumeMounts:
        - name: secret-rethinkdb
          mountPath: /secrets/rethinkdb/
          readOnly: true
        - name: secret-sendgrid
          mountPath: /secrets/sendgrid/
          readOnly: true
        - name: secret-zendesk
          mountPath: /secrets/zendesk/
          readOnly: true
      volumes:
        - name: secret-rethinkdb
          secret:
            secretName: rethinkdb-password
        - name: secret-sendgrid
          secret:
            secretName: sendgrid-api-key
        - name: secret-zendesk
          secret:
            secretName: zendesk-api-key
