# SageMathInc Travis-CI Configuration File
language: node_js
node_js:
  - "0.12"
#  - "iojs"

# Travis supports "global" and "build matrix" variables
# http://docs.travis-ci.com/user/environment-variables/
env:
  # not used. it should indicates that this test run checks the server side
  - MODE=server

# Installation and setup
before_script:
  # rethinkdb installation according to http://www.rethinkdb.com/docs/install/ubuntu/
  - source /etc/lsb-release
  - echo "deb http://download.rethinkdb.com/apt $DISTRIB_CODENAME main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
  - wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
  - sudo apt-get update -qq
  # besides rethinkdb, we need at least python-yaml
  - sudo apt-get install rethinkdb python-yaml --force-yes
  - rethinkdb --daemon
  - cd salvus
  - source salvus-env
  - npm install
  - ./make_coffee

# This is the actual testing, which runs in the same directory where `before_script` did end up in.
# A non-zero exit code indicates a failure.
script:
  - npm test
