# CoCalc Travis-CI Configuration File
sudo: required
dist: xenial

services:
  - postgresql

language: "python"

node_js:
  - "8"

addons:
  postgresql: "10"
  apt:
    update: true
    packages:
      - "python-pip"
      - "python3-pip"
      - "python3-pytest"

# Travis supports "global" and "build matrix" variables
# http://docs.travis-ci.com/user/environment-variables/
env:
  matrix:
    - MODE=util
    #- MODE=sagews
    #- MODE=server

before_install: []

# installation and setup
before_script:
  - "source /etc/lsb-release"
  - "pip -V"
  - "pip3 -V"
  - "python -V"
  - "nvm install v5.11"
  - "node --version"
  - "pytest --version"

# the setup & compilation of SMC
install:
  - "cd src"
  - "source smc-env"
  - "npm run make"

# This is the actual testing, which runs in the same directory where `before_script` did end up in.
# A non-zero exit code indicates a failure.
# npm test is the usual, but we also run coverage reporting
script:
  - 'if [[ $MODE = "sagews" ]]; then cd ~/smc/src/smc_sagews/smc_sagews/; python -m pytest tests/; fi'
  - 'if [[ $MODE = "webapp" ]]; then cd ~/smc/src/smc-webapp/; npm run test; fi'
  - 'if [[ $MODE = "server" ]]; then npm run coveralls; fi'
  - 'if [[ $MODE = "util"   ]]; then cd ~/smc/src/smc-util/; npm test; fi'

# send coverage report over to https://coveralls.io
#after_success:
#  - if [[ $MODE = "server" ]]; then sh -c 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'; fi

notifications:
  email:
    recipients:
      - "hsy@sagemath.com"
    on_success: change
    on_failure: change
