apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run : storagedaemon
  name: storagedaemon
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/storagedaemon
spec:
  replicas: 1
  selector:
    matchLabels:
      storage  : daemon
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
          storage  : daemon
    spec:
      containers:
      - image: "{image}"
        imagePullPolicy: {pull_policy}
        name: storagedaemon
        volumeMounts:
        - name: mnt
          mountPath: /node/info
        - name: hosts
          mountPath: /node/etc/hosts
        resources:
          requests:
            memory: "20Mi"
            cpu: "10m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mnt
        hostPath:
          path: /mnt/smc-storage/info/
      - name: hosts
        hostPath:
          path: /etc/hosts
      nodeSelector:
        volume: storage
