# This is really a template for generating the yaml that describes the deployments
# for each of the gluster nodes.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run : storage{number}
  name: storage{number}
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/storage
spec:
  replicas: 1
  selector:
    matchLabels:
      storage  : gluster
      instance : "{number}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
          storage  : gluster
          role     : replica
          instance : "{number}"
    spec:
      containers:
      - image: "{image}"
        imagePullPolicy: {pull_policy}
        name: gluster{number}
        ports:
          - name: rpcbind
            containerPort: 111
          - name: gluster1
            containerPort: 24007
          - name: gluster2
            containerPort: 24008
          - name: gluster3
            containerPort: 24009
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /brick
          name: gluster-brick
        resources:
          requests:
            memory: "100Mi"
            cpu: "40m"
          limits:
            memory: "1000Mi"
            cpu: "500m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gluster-brick
        gcePersistentDisk:
          fsType: ext4
          pdName: {pd_name}
