# This is really a template for generating the yaml that describes the deployments
# for each of the rethinkdb nodes.  The template format is just Python's and replaces
# {number} by a number.  That's it.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run : rethinkdb{number}
  name: rethinkdb{number}
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/rethinkdb
spec:
  replicas: 1
  selector:
    matchLabels:
      db       : rethinkdb
      role     : replica
      instance : "{number}"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
          db       : rethinkdb
          role     : replica
          instance : "{number}"
    spec:
      containers:
      - image: gcr.io/sage-math-inc/rethinkdb:0.12
        imagePullPolicy: Always # IfNotPresent
        name: rethinkdb0
        ports:
        - containerPort: 28015
          name: driver-port
        - containerPort: 29015
          name: cluster-port
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: rethinkdb-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - gcePersistentDisk:
          fsType: ext4
          pdName: kubetest-rethinkdb-{number}
        name: rethinkdb-storage
