apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: null
  generation: 1
  labels:
    run: rethinkdb-proxy
  name: rethinkdb-proxy
  selfLink: /apis/extensions/v1beta1/namespaces/deployments/rethinkdb-proxy
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      run: rethinkdb-proxy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rethinkdb-proxy
    spec:
      containers:
      - image: {image}
        imagePullPolicy: Always
        name: rethinkdb-proxy
        terminationMessagePath: /dev/termination-log
        env:
        - name: INITIAL_PASSWORD
          value: {initial_password}
        ports:
        - containerPort: 28015
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
