apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx2
    image: nginx
    volumeMounts:
    - name: test3
      mountPath: /share
    ports:
    - containerPort: 80
  volumes:
  - name: test3
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "test-project2/c.share"
        size   : "3000m"
  nodeSelector:
    volume: storage

