apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    - name: test2
      mountPath: /data2
    - name: test3
      mountPath: /share
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "test-projet/a.zfs"
        size   : "3000m"
  - name: test2
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "test-project2/b.zfs"
        size   : "3000m"
  - name: test3
    flexVolume:
      driver : "smc/smc-storage"
      options:
        server : '10.246.73.4:/projects'
        path   : "test-project2/c.share"
        size   : "3000m"
  nodeSelector:
    volume: storage