apiVersion: v1
kind: Pod
metadata:
  name: test3
spec:
  containers:
  - name: test3
    image: nginx
    volumeMounts:
    - name: share
      mountPath: /share
    ports:
    - containerPort: 80
  volumes:
  - name: share
    flexVolume:
      driver : "smc/smc-storage"
      options:
        namespace : 'test'
        server    : 'storage1'
        path      : "test.share"
        size      : "3000m"

