# This workflow will do a clean installation of node dependencies, build the source code and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Make all packages and run their unit tests

# newer commits in the same PR abort running ones for the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
          cache: "npm"
          cache-dependency-path: |
            src/packages/frontend/package-lock.json
            src/packages/backend/package-lock.json
            src/packages/hub/package-lock.json
            src/packages/util/package-lock.json
            src/packages/sync/package-lock.json
            src/packages/assets/package-lock.json
            src/packages/project/package-lock.json
            src/packages/server/package-lock.json
            src/packages/static/package-lock.json
            src/packages/database/package-lock.json
            src/packages/next/package-lock.json
            src/packages/cdn/package-lock.json

      - run: cd src; npm run make
      - run: cd src; npm run test
