# This watches for large file size changes in PR's.
# See https://github.com/adobe/sizewatcher#github-actions
name: Watch for Large File Size Changes

# newer commits in the same PR abort running ones for the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      # ---------- this runs sizewatcher ------------
      - run: npx @adobe/sizewatcher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
